class ROUTES:
    ROOT="/"
    ALL_IDS = "/all-ids"
    MOISTURE="/moisture/{ID}"
    PUMP_PERCENTAGE="/pump-percentage/{ID}"
    NEXT_WATER_TIME="/next-water-time/{ID}"
    PUMP_ON="/pump-on/{ID}"
    PUMP_OFF = "/pump-ofF/{ID}"
    UPDATE_PUMP_PERCENTAGE="update-pump-percentage/{ID}"
    UPDATE_ALL_PUMPS_PERCENTAGE="update-all_pumps-percentage"
    ALL_PUMPS_OFF = "/all-pumps-off"
    ALL_PUMPS_ON = "/all-pumps-on"
