class ROUTES:
    ROOT = "/"
    ALL_IDS = "/all-ids"
    MOISTURE = "/moisture/{id}"
    PUMP_PERCENTAGE = "/pump-percentage/{id}"
    NEXT_WATER_TIME = "/next-water-time/{id}"
    PUMP_ON = "/pump-on/{id}"
    PUMP_OFF = "/pump-ofF/{id}"
    UPDATE_PUMP_PERCENTAGE = "update-pump-percentage/{id}"
    UPDATE_ALL_PUMPS_PERCENTAGE = "update-all_pumps-percentage"
    ALL_PUMPS_OFF = "/all-pumps-off"
    ALL_PUMPS_ON = "/all-pumps-on"
